# Generated by Django 5.2.3 on 2025-07-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
